#print('mohan','sohan','rohan')
#print('mohan','sohan','rohan',sep='')
#print('mohan','sohan','rohan',sep='-')
#print('mohan','sohan','rohan',sep='#')
#print('mohan','sohan','rohan',sep='###@')
print('mohan','sohan','rohan',sep=':')